# Generated by Django 4.2 on 2023-05-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0002_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(choices=[('young', '10~20'), ('youngn adult', '20~30'), ('adult', '30~40'), ('senior', '40~50')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.CharField(choices=[('low', '140cm~150cm'), ('middle', '150cm~160cm'), ('high', '160cm~170cm'), ('super', '170cm~180cm')], max_length=20),
        ),
    ]
