# Generated by Django 4.2 on 2023-05-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0003_alter_customuser_age_alter_customuser_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(),
        ),
    ]
