# Generated by Django 4.2 on 2023-05-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0004_alter_customuser_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
