# Generated by Django 4.2 on 2023-05-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0005_remove_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
